/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import game.GameBoard;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author kalva
 */
public class BoardSizeFormDialog extends javax.swing.JDialog {
    
    public static GameBoard board;
    
    /**
     * Creates new form BoardSizeFormDialog
     */
    public BoardSizeFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBoardSizeHeader = new javax.swing.JLabel();
        cbRowSize = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbColumnSize = new javax.swing.JComboBox<>();
        lbWarning = new javax.swing.JLabel();
        btAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dimensiones del tablero");

        lbBoardSizeHeader.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbBoardSizeHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbBoardSizeHeader.setText("Ingrese las dimensiones del tablero de juego");

        cbRowSize.setBackground(new java.awt.Color(255, 255, 255));
        cbRowSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbRowSize.setForeground(new java.awt.Color(0, 0, 0));
        cbRowSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("X");

        cbColumnSize.setBackground(new java.awt.Color(255, 255, 255));
        cbColumnSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbColumnSize.setForeground(new java.awt.Color(0, 0, 0));
        cbColumnSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        lbWarning.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        lbWarning.setForeground(new java.awt.Color(255, 255, 255));
        lbWarning.setText("¡Ya casi empezamos!");

        btAccept.setBackground(new java.awt.Color(255, 255, 255));
        btAccept.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btAccept.setForeground(new java.awt.Color(51, 51, 51));
        btAccept.setText("Aceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cbRowSize, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbColumnSize, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbBoardSizeHeader, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(lbWarning)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(lbBoardSizeHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbWarning)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRowSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbColumnSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(btAccept)
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // TODO add your handling code here:
        //Añadir el id al player, pero primero hacer la valoración desde aquí.(USO DE EXCEPCIONES)
        int rowSize = Integer.parseInt((String) cbRowSize.getSelectedItem());
        int columnSize = Integer.parseInt((String) cbColumnSize.getSelectedItem());
        board = new GameBoard(rowSize, columnSize);
        
        hide();
        GameModeFormDialog gameMode = new GameModeFormDialog((JFrame) this.getParent(), true);
        gameMode.setVisible(true);
    }//GEN-LAST:event_btAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JComboBox<String> cbColumnSize;
    private javax.swing.JComboBox<String> cbRowSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBoardSizeHeader;
    private javax.swing.JLabel lbWarning;
    // End of variables declaration//GEN-END:variables
}
