/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JFrame;
import model.BaseComputer;
import model.HardComputer;
import model.MediumComputer;

/**
 *
 * @author kalva
 */
public class ComputerDificultyFormDialog extends javax.swing.JDialog {

    /**
     * Creates new form ComputerDificultyFormDialog
     */
    public ComputerDificultyFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDificulties = new javax.swing.ButtonGroup();
        lbComputerLevel = new javax.swing.JLabel();
        lbComputerLevelLogo = new javax.swing.JLabel();
        rbEasy = new javax.swing.JRadioButton();
        rbHard = new javax.swing.JRadioButton();
        rbMedium = new javax.swing.JRadioButton();
        lbSubHeader = new javax.swing.JLabel();
        btAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dificultad del contrincante");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbComputerLevel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbComputerLevel.setForeground(new java.awt.Color(255, 255, 255));
        lbComputerLevel.setText("Selecciona la dificultad de la computadora");

        lbComputerLevelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CompDifLogo.png"))); // NOI18N

        rbEasy.setBackground(new java.awt.Color(255, 255, 255));
        bgDificulties.add(rbEasy);
        rbEasy.setForeground(new java.awt.Color(51, 51, 51));
        rbEasy.setText("Fácil");

        rbHard.setBackground(new java.awt.Color(255, 255, 255));
        bgDificulties.add(rbHard);
        rbHard.setForeground(new java.awt.Color(51, 51, 51));
        rbHard.setText("Difícil");

        rbMedium.setBackground(new java.awt.Color(255, 255, 255));
        bgDificulties.add(rbMedium);
        rbMedium.setForeground(new java.awt.Color(51, 51, 51));
        rbMedium.setText("Medio");

        lbSubHeader.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbSubHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbSubHeader.setText("Elije a tu contrincante sabiamente");

        btAccept.setBackground(new java.awt.Color(255, 255, 255));
        btAccept.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btAccept.setForeground(new java.awt.Color(51, 51, 51));
        btAccept.setText("Aceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lbComputerLevelLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lbComputerLevel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lbSubHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(rbEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbHard, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbComputerLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbComputerLevelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSubHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEasy)
                    .addComponent(rbMedium)
                    .addComponent(rbHard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btAccept)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // TODO add your handling code here:
        BaseComputer computer = null;
        
        if (rbEasy.isSelected()) {
            computer = new BaseComputer(BoardSizeFormDialog.board);
        } else if (rbMedium.isSelected()) {
            computer = new MediumComputer(BoardSizeFormDialog.board);
        } else {
            computer = new HardComputer(BoardSizeFormDialog.board);
        }
        
        
        hide();
        GameFormDialog gameDialog = new GameFormDialog((JFrame) this.getParent(), true);
        gameDialog.setVisible(true);
    }//GEN-LAST:event_btAcceptActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GameModeFormDialog gameMode = new GameModeFormDialog((JFrame) this.getParent(), true);
        dispose();
        gameMode.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDificulties;
    private javax.swing.JButton btAccept;
    private javax.swing.JLabel lbComputerLevel;
    private javax.swing.JLabel lbComputerLevelLogo;
    private javax.swing.JLabel lbSubHeader;
    private javax.swing.JRadioButton rbEasy;
    private javax.swing.JRadioButton rbHard;
    private javax.swing.JRadioButton rbMedium;
    // End of variables declaration//GEN-END:variables
}
