/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import game.GameBoard;
import game.GameMode;
import game.TwoPlayersMode;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import model.Player;

/**
 *
 * @author kalva
 */
public class GameFormDialog extends javax.swing.JDialog {

    GameMode game;

    /**
     * Creates new form GameFormDialog
     */
    public GameFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        GameBoard board = BoardSizeFormDialog.board;
        game = new TwoPlayersMode(board, Player1ListDialog.player1, Player2ListDialog.player2);
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        pnBoard.setAlignmentY(SwingConstants.CENTER);
        pnBoard.setAlignmentX(SwingConstants.CENTER);
        pnBoard.setLayout(new GridLayout(board.rowSize(), board.columnSize()));
        createHeader();
        createGameBoard(board);
        createFooter();
    }

    private void createHeader() {
        lbGameHeader.setText(game.gameBoardHeader());
        lbGameHeader.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void createFooter() {
        lbGameFooter.setText(game.playersTurnSymbol() + " Turno");
        lbGameFooter.setHorizontalAlignment(SwingConstants.CENTER);
    }

    private void createGameBoard(GameBoard board) {
        pnBoard.removeAll();
        javax.swing.JLabel temp = null;
        int rowSize = board.rowSize();
        int columnSize = board.columnSize();

        //Impresión de prueba
        System.out.println(board.getBoard());
        System.out.println("Row size: " + rowSize);
        System.out.println("Column size: " + columnSize);

        for (int r = 0; r < rowSize; r++) {
            for (int c = 0; c < columnSize; c++) {
                temp = new JLabel(board.getElement(r, c) + " ");
                temp.setFont(new java.awt.Font("Tahoma", 0, 24));
                temp.setForeground(Color.white);
                temp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));
                temp.setSize(800, 800);

                if (((((r % 2) == 0)) && (((c % 2) != 0))) || ((((r % 2) != 0)) && (((c % 2) == 0)))) {
                    javax.swing.JLabel tempLabel = temp;
                    int row = r;
                    int col = c;
                    temp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            addLine(board, tempLabel, row, col);
                        }
                    });
                    temp = tempLabel;
                }
                pnBoard.add(temp);
            }
        }
    }

    private void addLine(GameBoard board, JLabel tempLabel, int row, int col) {
        boolean[] lineState = game.addLine(row, col);

        if (lineState[0]) { //lineState[0] = lineAdded
            tempLabel.setText(board.lineType(row));

            //Line color
            if (game.playersTurnSymbol() == "J1") {
                tempLabel.setForeground(Color.RED);
            } else {
                tempLabel.setForeground(Color.cyan);
            }

            if (!lineState[1]) { //lineState[1] = Won quadrant
                createFooter();

            } else {
                createHeader();
                createGameBoard(board);
                
                if (board.fullBoard()) {//lineState[0] = wonGame
                    JOptionPane.showMessageDialog(null, game.gameResult());
                    dispose();
                }
            }

            System.out.println(board.getBoard());
        } else {
            System.out.println("NO PUEDES AGREGAR UN LUGAR DONDE YA ESTA SELECCIONADO");
        }

    }

//    TRABAJAR EN LA LÓGICA DE COMIENZO ALERATORIO, POR LO MOMENTOS NO LA SIENTO TAN CUERENTE SEGÚN EL MANEJO DEL JUEGO
//    private String randomSymbol() {
//        int randomNumber = (int) (Math.floor(Math.random() * PLAYERS_SYMBOLS.length));
//        String symbol = PLAYERS_SYMBOLS[randomNumber];
//        removeSymbol(randomNumber);
//
//        return symbol;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBoard = new javax.swing.JPanel();
        lbGameHeader = new javax.swing.JLabel();
        lbGameFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana de juego");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnBoard.setBackground(new java.awt.Color(102, 102, 102));
        pnBoard.setForeground(new java.awt.Color(255, 255, 255));
        pnBoard.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnBoardLayout = new javax.swing.GroupLayout(pnBoard);
        pnBoard.setLayout(pnBoardLayout);
        pnBoardLayout.setHorizontalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnBoardLayout.setVerticalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        lbGameHeader.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbGameHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbGameHeader.setText("Header");

        lbGameFooter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGameFooter.setForeground(new java.awt.Color(255, 255, 255));
        lbGameFooter.setText("Footer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGameHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(lbGameFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbGameHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbGameFooter)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbGameFooter;
    private javax.swing.JLabel lbGameHeader;
    private javax.swing.JPanel pnBoard;
    // End of variables declaration//GEN-END:variables
}
