/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import game.GameBoard;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author kalva
 */
public class GameModeFormDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form GameModeFormDialog
     */
    public GameModeFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btTwoPlayersMode = new javax.swing.JButton();
        lbGameModeHeader = new javax.swing.JLabel();
        btComputerMode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modalidad de juego");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GameModeLogo.png"))); // NOI18N

        btTwoPlayersMode.setBackground(new java.awt.Color(255, 255, 255));
        btTwoPlayersMode.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btTwoPlayersMode.setForeground(new java.awt.Color(51, 51, 51));
        btTwoPlayersMode.setText("Jugador VS Jugador");
        btTwoPlayersMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTwoPlayersModeActionPerformed(evt);
            }
        });

        lbGameModeHeader.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbGameModeHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbGameModeHeader.setText("Indique la modalidad de juego");

        btComputerMode.setBackground(new java.awt.Color(255, 255, 255));
        btComputerMode.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btComputerMode.setForeground(new java.awt.Color(51, 51, 51));
        btComputerMode.setText("Jugador VS Computadora");
        btComputerMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComputerModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btTwoPlayersMode, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btComputerMode))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lbGameModeHeader)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbGameModeHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTwoPlayersMode)
                    .addComponent(btComputerMode))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btComputerModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComputerModeActionPerformed
        // TODO add your handling code here:
        ComputerDificultyFormDialog computerDificulty = new ComputerDificultyFormDialog((JFrame) this.getParent(), true);
        hide();
        computerDificulty.setVisible(true);
    }//GEN-LAST:event_btComputerModeActionPerformed

    private void btTwoPlayersModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTwoPlayersModeActionPerformed
        // TODO add your handling code here:
        Player2ListDialog window = new Player2ListDialog((JFrame) this.getParent(), true);
        hide();
        window.setVisible(true);
    }//GEN-LAST:event_btTwoPlayersModeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComputerMode;
    private javax.swing.JButton btTwoPlayersMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbGameModeHeader;
    // End of variables declaration//GEN-END:variables
}
