/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JFrame;
import main.Menu;
import model.Player;

/**
 *
 * @author kalva
 */
public class PlayerFormDialog extends javax.swing.JDialog {

    /**
     * Creates new form PlayerFormDialog
     */
    public PlayerFormDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPlayerIDHeader = new javax.swing.JLabel();
        lbWarning = new javax.swing.JLabel();
        tfPlayerID = new javax.swing.JTextField();
        btAccept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear un usuario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbPlayerIDHeader.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbPlayerIDHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbPlayerIDHeader.setText("Ingrese un indentificador para el usuario");

        lbWarning.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbWarning.setForeground(new java.awt.Color(204, 204, 204));
        lbWarning.setText("Número de caracteres: Mínimo 4, máximo 8");

        tfPlayerID.setBackground(new java.awt.Color(255, 255, 255));
        tfPlayerID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPlayerID.setForeground(new java.awt.Color(51, 51, 51));

        btAccept.setBackground(new java.awt.Color(255, 255, 255));
        btAccept.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btAccept.setForeground(new java.awt.Color(51, 51, 51));
        btAccept.setText("Aceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Player1CreationLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPlayerID)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btAccept))
                            .addComponent(lbPlayerIDHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbWarning)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lbPlayerIDHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbWarning)
                        .addGap(31, 31, 31)
                        .addComponent(tfPlayerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btAccept)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // TODO add your handling code here:
        String playerID = tfPlayerID.getText();
        //Hacer la evaluación aqui sobre la longitud del indentificador
        Player newPlayer = new Player(playerID, 0);
        Menu.playerList.addPlayer(newPlayer);
        //Enviar el jugador al juego
        dispose();
        BoardSizeFormDialog boardDialog = new BoardSizeFormDialog((JFrame) this.getParent(), true);
        boardDialog.setVisible(true);
    }//GEN-LAST:event_btAcceptActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        PlayersMenuDialog playersMenu = new PlayersMenuDialog((JFrame) this.getParent(), true);
        dispose();
        playersMenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPlayerIDHeader;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JTextField tfPlayerID;
    // End of variables declaration//GEN-END:variables
}
