/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import main.Menu;
import model.Player;

/**
 *
 * @author kalva
 */
public class Player2ListDialog extends javax.swing.JDialog {
    
    public static Player player2;
    private DefaultListModel model;

    /**
     * Creates new form PlayerListDialog
     */
    public Player2ListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        model = new DefaultListModel();
        fillList();
    }

    private void fillList() {
        for (int i = 0; i < Menu.playerList.getSize(); i++) {
            model.addElement(Menu.playerList.getPlayer(i));
        }
        ltPlayers.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSubHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltPlayers = new javax.swing.JList<>();
        lbExistingUsersHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de usuarios disponibles 2");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbSubHeader.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbSubHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbSubHeader.setText("Recuerde no elegir el mismo usuario que el jugador 1");

        ltPlayers.setBackground(new java.awt.Color(102, 102, 102));
        ltPlayers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ltPlayers.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        ltPlayers.setForeground(new java.awt.Color(255, 255, 255));
        ltPlayers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ltPlayersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ltPlayers);

        lbExistingUsersHeader.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbExistingUsersHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbExistingUsersHeader.setText("Seleccione un usuario para el jugador 2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/P2ListLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lbSubHeader))
                            .addComponent(lbExistingUsersHeader))
                        .addGap(52, 52, 52)))
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbExistingUsersHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSubHeader)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ltPlayersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ltPlayersValueChanged
        // TODO add your handling code here:
        player2 = ((Player) model.getElementAt(ltPlayers.getSelectedIndex()));
        player2.setPlayerSymbol("J2");
        //Enviar el jugador al modo de juego.
        dispose();
        GameFormDialog game = new GameFormDialog((JFrame) this.getParent(), true);
        game.setVisible(true);
    }//GEN-LAST:event_ltPlayersValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        GameModeFormDialog gameMode = new GameModeFormDialog((JFrame) this.getParent(), true);
        dispose();
        gameMode.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbExistingUsersHeader;
    private javax.swing.JLabel lbSubHeader;
    private javax.swing.JList<String> ltPlayers;
    // End of variables declaration//GEN-END:variables
}
