/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author kalva
 */
public class PlayersMenuDialog extends javax.swing.JDialog {

    /**
     * Creates new form BoardSizeFormDialog
     */
    public PlayersMenuDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt = new javax.swing.JButton();
        btCreateUser = new javax.swing.JButton();
        lbPlayerMenuHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selección de jugadores");

        bt.setBackground(new java.awt.Color(255, 255, 255));
        bt.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        bt.setForeground(new java.awt.Color(51, 51, 51));
        bt.setText("Elegir usuario existente");
        bt.setActionCommand("Elejir jugador existente");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });

        btCreateUser.setBackground(new java.awt.Color(255, 255, 255));
        btCreateUser.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        btCreateUser.setForeground(new java.awt.Color(51, 51, 51));
        btCreateUser.setText("Crear un nuevo usuario");
        btCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateUserActionPerformed(evt);
            }
        });

        lbPlayerMenuHeader.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbPlayerMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbPlayerMenuHeader.setText("Seleccione el tipo de usaurio que desee");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Player1Logo.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lbPlayerMenuHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(bt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCreateUser)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPlayerMenuHeader)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt)
                    .addComponent(btCreateUser))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
        Player1ListDialog window = new Player1ListDialog((JFrame) this.getParent(), true);
        hide();
        window.setVisible(true);
    }//GEN-LAST:event_btActionPerformed

    private void btCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateUserActionPerformed
        // TODO add your handling code here:
        PlayerFormDialog window = new PlayerFormDialog((JFrame) this.getParent(), true);
        hide();
        window.setVisible(true);
    }//GEN-LAST:event_btCreateUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JButton btCreateUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbPlayerMenuHeader;
    // End of variables declaration//GEN-END:variables
}
